### PR TITLE
Open links into a new tab in Outline

### PR DESCRIPTION
**Pull request by giantoppai**
Add a way to right click a link to an article and select "Open Link in Outline" to do so.

### CODE REVIEW

**Comment by SaintWacko** [comment]
Well, I'm glad I checked the PRs before doing this myself...

**Comment by giantoppai** [comment]
@okhwaja

**Comment by okhwaja** [comment]
Hi @giantoppai , sorry I didn't see this earlier. This is a great addition!

Merging and deploying soon

**Comment by okhwaja** [comment]
Deployed, thanks @giantoppai !

**Comment by giantoppai** [comment]
You're welcome!

**Pull request merged**
